version: '3.8'

services:
  web:
    build: .
    command: gunicorn core.wsgi -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/codes
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECRET_KEY=django-insecure-ex3e10@tkq3d9tob%$1zr_s=d^dpdp7u^7tjjth5&^-07tlx^@"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"  
      
volumes:
  postgres_data: