# Generated by Django 5.0.4 on 2024-05-08 01:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('poetry', 'Poetry'), ('story', 'Story'), ('essay', 'Essay'), ('article', 'Article'), ('other', 'Other'), ('tutorial', 'Tutorial'), ('exploration', 'Exploration'), ('movie_review', 'Movie Review'), ('book_review', 'Book Review')], default='writing', max_length=200)),
                ('tags', models.ManyToManyField(to='blog.tag')),
            ],
        ),
    ]
