# Generated by Django 5.0.4 on 2024-06-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_slug_writing_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writing',
        ),
    ]
